# Backtesting Configuration
# Main configuration file for backtesting parameters

# General Backtesting Settings
backtest:
  initial_capital: 10000.0
  commission: 0.001  # 0.1% per trade
  slippage: 0.0005  # 0.05% slippage
  use_leverage: false
  max_leverage: 1.0
  
  # Data settings
  data:
    symbol: "BTC/USDT"  # Primary symbol for testing
    additional_symbols:  # For future multi-asset support
      - "ETH/USDT"
      - "SOL/USDT"
    timeframe: "4h"  # Primary timeframe
    additional_timeframes:
      - "1h"
      - "1d"
    start_date: "2021-01-01"
    end_date: null  # null means use latest data
    
  # Walk-forward analysis settings
  walk_forward:
    enabled: true
    in_sample_ratio: 0.7  # 70% for training
    out_sample_ratio: 0.3  # 30% for testing
    window_type: "rolling"  # rolling or expanding
    n_splits: 5

# Risk Management Settings
risk_management:
  max_position_size: 0.95  # Maximum 95% of capital in one position
  max_drawdown_limit: 0.25  # Stop trading if drawdown exceeds 25%
  position_sizing:
    method: "fixed_fractional"  # fixed_fractional, kelly, volatility_based
    risk_per_trade: 0.02  # Risk 2% per trade
    
# Performance Criteria for Optimization
performance_criteria:
  primary_metric: "sharpe_ratio"  # Main metric to optimize
  secondary_metrics:
    - "total_return"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
  constraints:
    min_trades: 20  # Minimum trades for valid backtest
    max_drawdown: 0.30  # Maximum acceptable drawdown
    min_win_rate: 0.35  # Minimum win rate
    min_sharpe_ratio: 0.5

# Output Settings
output:
  save_trades: true
  save_equity_curve: true
  save_metrics: true
  generate_report: true
  output_directory: "backend/backtesting/data/results"
  report_format: ["html", "pdf", "json"]
  
# Logging Settings
logging:
  level: "INFO"
  file: "backend/backtesting/logs/backtest.log"
  console: true
