# Parameter Optimization Ranges for Trading Strategies
# Defines the parameter search space for each strategy

strategies:
  bollinger_bands:
    parameters:
      bb_length:
        min: 10
        max: 30
        step: 5
        type: "int"
      bb_std:
        min: 1.5
        max: 3.0
        step: 0.5
        type: "float"
      rsi_length:
        min: 10
        max: 20
        step: 2
        type: "int"
      rsi_oversold:
        min: 20
        max: 40
        step: 5
        type: "int"
      rsi_overbought:
        min: 60
        max: 80
        step: 5
        type: "int"
        
  rsi_divergence:
    parameters:
      rsi_length:
        min: 10
        max: 20
        step: 2
        type: "int"
      rsi_sma_fast:
        min: 3
        max: 10
        step: 1
        type: "int"
      rsi_sma_slow:
        min: 8
        max: 15
        step: 1
        type: "int"
      rsi_oversold:
        min: 20
        max: 35
        step: 5
        type: "int"
      rsi_overbought:
        min: 65
        max: 80
        step: 5
        type: "int"
      momentum_lookback:
        min: 3
        max: 10
        step: 1
        type: "int"
      divergence_lookback:
        min: 10
        max: 30
        step: 5
        type: "int"
        
  macd_momentum:
    parameters:
      macd_fast:
        min: 8
        max: 16
        step: 2
        type: "int"
      macd_slow:
        min: 20
        max: 30
        step: 2
        type: "int"
      macd_signal:
        min: 6
        max: 12
        step: 1
        type: "int"
      momentum_period:
        min: 10
        max: 20
        step: 2
        type: "int"
      atr_period:
        min: 10
        max: 20
        step: 2
        type: "int"
      volume_threshold:
        min: 1.2
        max: 2.0
        step: 0.2
        type: "float"
        
  volatility_breakout_short:
    parameters:
      atr_period:
        min: 10
        max: 20
        step: 2
        type: "int"
      lookback_period:
        min: 15
        max: 30
        step: 5
        type: "int"
      volume_multiplier:
        min: 1.5
        max: 3.0
        step: 0.5
        type: "float"
      rsi_period:
        min: 10
        max: 20
        step: 2
        type: "int"
      rsi_extreme:
        min: 15
        max: 30
        step: 5
        type: "int"
      atr_stop_multiplier:
        min: 1.5
        max: 3.0
        step: 0.5
        type: "float"
      atr_trail_multiplier:
        min: 1.0
        max: 2.0
        step: 0.25
        type: "float"
        
  ichimoku_cloud:
    parameters:
      tenkan_period:
        min: 7
        max: 12
        step: 1
        type: "int"
      kijun_period:
        min: 20
        max: 30
        step: 2
        type: "int"
      senkou_b_period:
        min: 44
        max: 60
        step: 4
        type: "int"
      displacement:
        min: 20
        max: 30
        step: 2
        type: "int"
        
  parabolic_sar:
    parameters:
      start:
        min: 0.01
        max: 0.03
        step: 0.005
        type: "float"
      increment:
        min: 0.01
        max: 0.03
        step: 0.005
        type: "float"
      maximum:
        min: 0.15
        max: 0.25
        step: 0.05
        type: "float"
        
  fibonacci_retracement:
    parameters:
      lookback_period:
        min: 30
        max: 100
        step: 10
        type: "int"
      fib_levels:
        type: "list"
        options:
          - [0.236, 0.382, 0.5, 0.618]
          - [0.236, 0.382, 0.5, 0.618, 0.786]
          - [0.382, 0.5, 0.618]
          
  gaussian_channel:
    parameters:
      period:
        min: 15
        max: 30
        step: 5
        type: "int"
      std_dev:
        min: 1.5
        max: 3.0
        step: 0.5
        type: "float"
      adaptive:
        type: "bool"
        options: [true, false]

# Optimization Algorithm Settings
optimization:
  method: "grid_search"  # grid_search, bayesian
  grid_search:
    exhaustive: false  # If true, test all combinations
    max_combinations: 1000
  bayesian:
    n_initial_points: 20
    n_calls: 100
    acq_func: "EI"  # Expected Improvement
    
# Multi-objective Optimization Settings
multi_objective:
  enabled: true
  objectives:
    - metric: "sharpe_ratio"
      weight: 0.4
      direction: "maximize"
    - metric: "total_return"
      weight: 0.3
      direction: "maximize"
    - metric: "max_drawdown"
      weight: 0.3
      direction: "minimize"
