# Optimized Strategy Parameters
# These parameters have been optimized through backtesting on BTC/USDT 4h data
# Last optimization: 2025-09-14

strategies:
  bollinger_bands:
    description: "Bollinger Bands Mean Reversion - Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        bb_length: 25
        bb_std: 2.5
        rsi_length: 18
        rsi_oversold: 40
        rsi_overbought: 80

    
  rsi_divergence:
    description: "RSI Momentum Divergence - Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        rsi_length: 18
        rsi_sma_fast: 5
        rsi_sma_slow: 12
        rsi_oversold: 25
        rsi_overbought: 75
        momentum_lookback: 7
        divergence_lookback: 20


  macd_momentum:
    description: "MACD Momentum Crossover - Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        macd_fast: 14
        macd_slow: 28
        macd_signal: 10
        momentum_period: 18
        atr_period: 20
        volume_threshold: 1.6


  volatility_breakout_short:
    description: "Volatility Breakout Short -Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        atr_period: 14
        lookback_period: 20
        rsi_period: 14
        rsi_extreme: 25
        atr_stop_multiplier: 2.0
        atr_trail_multiplier: 1.5
        
  ichimoku_cloud:
    description: "Ichimoku Cloud Breakout - Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        tenkan_period: 11
        kijun_period: 28
        senkou_b_period: 56
        displacement: 28
        
  parabolic_sar:
    description: "Parabolic SAR Trend Following - Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        start: 0.01
        increment: 0.01
        maximum: 0.15
        
  fibonacci_retracement:
    description: "Fibonacci Retracement - Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        lookback_period: 50
        fib_levels: [0.236, 0.382, 0.5, 0.618, 0.786]
        
  gaussian_channel:
    description: "Gaussian Channel - Optimized for BTC/USDT 4h"
    optimized_parameters:
      default:
        period: 25
        std_dev: 2.5
        adaptive: true
