strategies:
  full_confirmation_tk+span_exit_llm_btc_4h:
    name: Full Confirmation TK+Span Exit
    description: All conditions + Chikou confirmations, exit on TK cross down AND
      SpanA<SpanB
    enabled: true
    timeframes:
    - 1h
    - 4h
    symbols:
    - BTC/USDT
    signal_conditions:
      buy_conditions:
      - PriceAboveCloud
      - TenkanAboveKijun
      - SpanAaboveSpanB
      - ChikouAboveCloud
      - ChikouAbovePrice
      sell_conditions:
      - TenkanBelowKijun
      - SpanAbelowSpanB
      buy_logic: AND
      sell_logic: AND
    ichimoku_parameters:
      tenkan_period: 7
      kijun_period: 20
      senkou_b_period: 48
      chikou_offset: 20
      senkou_offset: 20
    risk_management:
      stop_loss_pct: 3.0
      take_profit_pct: 10.0
      close_on_sell_signal: true
      trailing_stop: false
      max_position_size_pct: 100.0
      risk_per_trade_pct: 5.0
    position_sizing:
      method: volatility
      fixed_size: 1000
