strategies:
  strategy_01:
    name: "Full Confirmation TK Exit default with 3% SL"
    description: "All conditions + Chikou confirmations, exit on TK cross down"
    enabled: true
    timeframes: [ "1h", "4h", "1d" ]
    symbols: [ "BTC/USDT" ]
    signal_conditions:
      buy_conditions: [ "PriceAboveCloud", "TenkanAboveKijun", "SpanAaboveSpanB", "ChikouAboveCloud", "ChikouAbovePrice" ]
      sell_conditions: [ "TenkanBelowKijun" ]
      buy_logic: "AND"
      sell_logic: "AND"
    ichimoku_parameters:
      tenkan_period: 9
      kijun_period: 26
      senkou_b_period: 52
      chikou_offset: 26
      senkou_offset: 26
    risk_management:
      stop_loss_pct: 3.0
      take_profit_pct: null
      close_on_sell_signal: true
      trailing_stop: false
      max_position_size_pct: 100.0
      risk_per_trade_pct: 3.0
    position_sizing:
      method: "fixed"
      fixed_size: 1000

  strategy_02:
    name: "Full Confirmation TK Exit modified with 3% SL"
    description: "All conditions + Chikou confirmations, exit on TK cross down"
    enabled: true
    timeframes: [ "1h", "4h", "1d" ]
    symbols: ["BTC/USDT"]
    signal_conditions:
      buy_conditions: ["PriceAboveCloud", "TenkanAboveKijun", "SpanAaboveSpanB", "ChikouAboveCloud", "ChikouAbovePrice"]
      sell_conditions: ["TenkanBelowKijun"]
      buy_logic: "AND"
      sell_logic: "AND"
    ichimoku_parameters:
      tenkan_period: 11
      kijun_period: 22
      senkou_b_period: 56
      chikou_offset: 26
      senkou_offset: 26
    risk_management:
      stop_loss_pct: 3.0
      take_profit_pct: null
      close_on_sell_signal: true
      trailing_stop: false
      max_position_size_pct: 100.0
      risk_per_trade_pct: 3.0
    position_sizing:
      method: "fixed"
      fixed_size: 1000

  strategy_03_SL-3:
    name: "Full Confirmation TK Exit SL 3%"
    description: "All conditions + Chikou confirmations, exit on TK cross down"
    enabled: true
    timeframes: [ "1h", "4h" ]
    symbols: [ "BTC/USDT" ]
    signal_conditions:
      buy_conditions: [ "PriceAboveCloud", "TenkanAboveKijun", "SpanAaboveSpanB", "ChikouAboveCloud", "ChikouAbovePrice" ]
      sell_conditions: [ "TenkanBelowKijun" ]
      buy_logic: "AND"
      sell_logic: "AND"
    ichimoku_parameters:
      tenkan_period: 9
      kijun_period: 26
      senkou_b_period: 52
      chikou_offset: 26
      senkou_offset: 26
    risk_management:
      stop_loss_pct: 5.0
      take_profit_pct: null
      close_on_sell_signal: true
      trailing_stop: false
      max_position_size_pct: 100.0
      risk_per_trade_pct: 5.0
    position_sizing:
      method: "fixed"
      fixed_size: 1000

  strategy_04_SL-4_90:
    name: "Full Confirmation TK Exit SL 4% with position size 90%"
    description: "All conditions + Chikou confirmations, exit on TK cross down"
    enabled: true
    timeframes: [ "1h", "4h" ]
    symbols: [ "BTC/USDT" ]
    signal_conditions:
      buy_conditions: [ "PriceAboveCloud", "TenkanAboveKijun", "SpanAaboveSpanB", "ChikouAboveCloud", "ChikouAbovePrice" ]
      sell_conditions: [ "TenkanBelowKijun" ]
      buy_logic: "AND"
      sell_logic: "AND"
    ichimoku_parameters:
      tenkan_period: 9
      kijun_period: 26
      senkou_b_period: 52
      chikou_offset: 26
      senkou_offset: 26
    risk_management:
      stop_loss_pct: 4.0
      take_profit_pct: null
      close_on_sell_signal: true
      trailing_stop: false
      max_position_size_pct: 90.0
      risk_per_trade_pct: 5.0
    position_sizing:
      method: "fixed"
      fixed_size: 1000

  strategy_05_SL-3_90:
    name: "Full Confirmation TK Exit SL 3% with position size 90%"
    description: "All conditions + Chikou confirmations, exit on TK cross down"
    enabled: true
    timeframes: [ "1h", "4h" ]
    symbols: [ "BTC/USDT" ]
    signal_conditions:
      buy_conditions: [ "PriceAboveCloud", "TenkanAboveKijun", "SpanAaboveSpanB", "ChikouAboveCloud", "ChikouAbovePrice" ]
      sell_conditions: [ "TenkanBelowKijun" ]
      buy_logic: "AND"
      sell_logic: "AND"
    ichimoku_parameters:
      tenkan_period: 9
      kijun_period: 26
      senkou_b_period: 52
      chikou_offset: 26
      senkou_offset: 26
    risk_management:
      stop_loss_pct: 5.0
      take_profit_pct: null
      close_on_sell_signal: true
      trailing_stop: false
      max_position_size_pct: 90.0
      risk_per_trade_pct: 5.0
    position_sizing:
      method: "fixed"
      fixed_size: 1000

  strategy_06_modifd:
    name: "Full Confirmation TK Exit with modified parameters"
    description: "All conditions + Chikou confirmations, exit on TK cross down"
    enabled: true
    timeframes: [ "1h", "4h" ]
    symbols: [ "BTC/USDT" ]
    signal_conditions:
      buy_conditions: [ "PriceAboveCloud", "TenkanAboveKijun", "SpanAaboveSpanB", "ChikouAboveCloud", "ChikouAbovePrice" ]
      sell_conditions: [ "TenkanBelowKijun" ]
      buy_logic: "AND"
      sell_logic: "AND"
    ichimoku_parameters:
      tenkan_period: 7
      kijun_period: 20
      senkou_b_period: 48
      chikou_offset: 20
      senkou_offset: 20
    risk_management:
      stop_loss_pct: 5.0
      take_profit_pct: null
      close_on_sell_signal: true
      trailing_stop: false
      max_position_size_pct: 100.0
      risk_per_trade_pct: 5.0
    position_sizing:
      method: "fixed"
      fixed_size: 1000